### ISSUE TITLE
Unable to create "works" with current version of sufia in HydraNorth2

### ISSUE THREAD

**Issue by murny** [ualbertalib/Hydranorth2#124]
With the current version of sufia 7.2 you are not able to upload/create any "works" from the UI. This is a pretty big breaking bug since this is a big portion of functionality for sufia.

This is due the `params` behaviour being changed in Rails 5. `ActionController::Parameters` now returns an Object instead of a Hash. You are required to `.to_h` the object to get an hash back. This now breaks the code found here when attempting to create a `BatchCreateJob`:
https://github.com/projecthydra/sufia/blob/v7.2.0/app/controllers/concerns/sufia/batch_uploads_controller_behavior.rb#L43-L48

This has been hotfixed in future commits in Sufia:
https://github.com/projecthydra/sufia/commit/a5b5e9fb87afbc91baf0a981cd4780e84ed0cb41

But currently no other releases have happened in 4 months since sufia 7.2 was released in Oct 1st, 2016? 

What to do?

-  Don't use rails 5?
- Point the sufia gem in our Gemfile to the master branch of github repo  (which has almost 300 commit since sufia 7.2...how much of a pain is that going to be? Plus tracking a gem to master is going to be painful as well). Looks like sufia 7.2-migration branch (https://github.com/projecthydra/sufia/tree/7.2-migration) has these bug fixes in them. Suppose we could track it against this branch or to a certain commit version too instead. Might be best solution.
- Fork Sufia and point it to our fork which has the fix instead maybe?
- Should we be pointing to Hyrax instead? This project doesn't appear to be any better either though? (but this is what hyku is doing since Dec 2016, it has since stop using sufia and is now pointing to hyrax's master branch instead)

(@mbarnett )

**Comment by mbarnett** [comment]
Yikes. We'll either need to fork 7.2 or get working against hyrax. Since we don't want to freeze on 7.2 we're going to have to tackle the pain of moving to hyrax sooner or later -- I'd vote for sooner.

**Comment by weiweishi** [comment]
I agree using Hyrax makes sense at this point, since that's where all the active development is happening.

**Comment by murny** [comment]
Has been fixed in #127 (Decided to upgrade to Sufia branch instead of hyrax (#125))
