### ISSUE TITLE
IST Setup Develop & Lightweight omniauth-SAML Gem Setup

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/Hydranorth2#129]
- We need to create new Metadata 
- Set up omniauth-SAML gem
- Ping Tyler w/ new metadata
- Tests

**Comment by murny** [comment]
Update on this. Leo from IST has added our SAML sp metadata for era-test.library.ualberta.ca to their uat login SAML metadata IdP. Will have to give this a test run to see if everything is working before moving on with this ticket. If all works we won't need shibboleth anymore.

Ideally you can change your hosts file on your local machine to take over era-test domain and this should just work in local dev.

**Comment by mbarnett** [comment]
Sweet
