### ISSUE TITLE
Fedora upgrade: Test migration process

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/Hydranorth2#148]
Complete the testing of the full migration from current HydraNorth to Fedora 4.7.2

**Comment by jefferya** [comment]
**Test tools (with information extracted from #106):**

(1) walking repository and verifying resources respond successfully - 
  * run on Fedora before fcr:backup and on Fedora 4.7.2 after fcr:restore (compare output) https://github.com/awoods/fcrepo-java-client-etc
    * e.g. java -jar fcrepo-java-client-etc-0.1.0-SNAPSHOT.jar -b http://localhost:8085/fcrepo/rest/ -u {$username} -p {$password} | tee  ~/dev/fcrepo-java-client-etc.log2

(2) Test using the import/export verify tool in conjunction with to new import/export tool meant to replace deprecated fcr:backup/fcr:restore
* https://github.com/fcrepo4-labs/fcrepo-import-export
* https://github.com/fcrepo4-labs/fcrepo-import-export-verify

**In the future - try the 4.6.2 to current (4.7.2+) Fedora migration using (import/export tool)[https://github.com/fcrepo4-labs/fcrepo-import-export]**
  * fcr:backup/fcr:restore are deprecated as per https://jira.duraspace.org/browse/FCREPO-2044?src=confmacro
  * "[fcr:backup/fcr:restore]... capability will continue to be available until the Import/Export functionality fully supports backup/restore use cases." - https://wiki.duraspace.org/display/FF/Fedora+4.7.1+Release+Notes





Notes:
* test (1) was successful - output before and after returned the same result with the same number of results and same ids.
