### ISSUE TITLE
Verify migrated objects

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/Hydranorth2#149]
In cooperation with the Metadata Team, verify metadata at the field level for a sample set of records (thesis and non-thesis). Zach will help with this - send him sample items when migration complete.

**Comment by jefferya** [comment]
Details on metadata changes due to the transition from Fedora 4.2 to above 4.3  [[1]](https://github.com/fcrepo4-exts/fcrepo4-upgrade-utils) and [[2]](https://groups.google.com/d/msg/fedora-tech/9eik_p0zPWY/BcglXSSEAAAJ) )

```
TechnicalMetadataMigrator: migrate technical metadata properties based on changes made in May 2015 to Fedora 4.3:
fedora:digest => premis:hasMessageDigest
fedora:mimeType => ebucore:hasMimeType
premis:hasOriginalName => ebucore:filename
```
