### ISSUE TITLE
Update code and gems in HydraNorth to work with Fedora 4.7.2

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/Hydranorth2#150]
Some issues have been identified (e.g. changes to response headers) and others are likely to emerge when testing is complete.

**Comment by jefferya** [comment]
An example of building a test environment to facilitate connecting HydraNorth to Fedora 4.7.2:

(1) Install HydraNorth Docker Image as per readme

(2) Install the Fedora 4.7.2 image from "https://github.com/fcrepo4-labs/fcrepo4-docker" as per readme. I didn't enable WebAC or audit . I followed the usage section. You can change the exposed ports via "-p 8083:8080 -p 9083:9080".

(3) Get the IP address of the Fedora container (e.g., docker inspect {$CID} | grep IPAddress)

(4) In the HydraNorth "config/fedora.yml" - change the "user", "password" (in fcrepo4-docker readme), and "url". The "url" should be the IP from #3 with port (if changed in #2), and fcrepo/rest (e.g.,  "http://127.0.0.2:8083/frepo/rest")

(5) Bounce rails (or restart HydraNorth Docker)

(6) HydraNorth Batch ingest sample data (these should end up in the Fedora 4.7.1 docker image)
  * rake migration:user_migration['lib/tasks/migration/test-metadata/users.txt']
  * rake migration:era_collection_community['lib/tasks/migration/test-metadata/community'] 
  * rake migration:era_collection_community['lib/tasks/migration/test-metadata/collection']
  * rake migration:eraitem['lib/tasks/migration/test-metadata']

(7) From the web interface, edit an object brings up a "content-type" error (issue with active-fedora 9.4.2) if the object has an attached file.

(8) If I update Gemfile.lock with a active-fedora 10+, then bundle install, I begin to have issues with hydra-access-controls (and so on and so forth). 

-----
cwant evaluating the viability of patching the Hydra side (Sufia 6.2 etc.) to work with Fedora 4.7.2
