### ISSUE TITLE
Update Dockerfile to switch to different base image

### ISSUE THREAD

**Issue by alexstrilets** [ualbertalib/Hydranorth2#152]
Docker file needs to be updated to switch from ualibraries/ruby_plus2.3.3 as we will not longer maintain that.

**Comment by murny** [comment]
What should it be switched too? Official ruby image?

From this
```
FROM ualibraries/ruby_plus2.3.3
```
to this ?
```
FROM ruby:2.3.4
```

**Comment by alexstrilets** [comment]
ualibraries/rubyhydra - base image for all hydra project derived from ruby:2.3.4
