### ISSUE TITLE
SPIKE: Blacklight Setup w/ Hydra-Works/Jupiter

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/Hydranorth2#163]
Within a timebox, try to get a basic blacklight set up working with the Jupiter prototype

**Comment by weiweishi** [comment]
@mbarnett I think we can call the work on this Spike completed. Could you please update this ticket with a link to your code, and documentation when it's ready?

**Comment by mbarnett** [comment]
Code has been living here until such time as we're ready to make it more "official" and move it into  ualberta: https://github.com/mbarnett/jupiter.

There's a significant amount of work remaining in terms of getting tests in place, documenting the architecture, usage, and the public API. My sense of things would be all work that belongs with this spike, meaning that I wouldn't call this spike completed until time has been put towards that. Alternatively, we could close this ticket and open a new one to track the documentation and testing work. I'm open to either.

**Comment by weiweishi** [comment]
I'm okay with keeping this ticket open until we have the tests and
documentation in place. And thanks for updating the ticket with link.


*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by mbarnett** [comment]
There's now a PR for both tests and documentation in the new Jupiter repository: https://github.com/ualbertalib/jupiter/pull/20
