### ISSUE TITLE
SPIKE: Wireframe

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/Hydranorth2#166]
### Description
This spike is to use a wireframe tool to create the first iteration of wireframes to reflect the important features captured in @leahvanderjagt's feature list (link to be updated)

### Scope
Must-have features from IR feature list 
 - Deposit form (single page) for multi-files
 - Item view
 - Search and search result
 - Collection view
 - Community view
 - Browse
 - Facet

### Expected Outcome
 - [ ] Wireframes for the must-have features as part of the design phase. 
 - [ ] Documentation of tools and processes to create wireframes

**Comment by murny** [comment]
For a wireframming/mockup tool, I have used [balsamiq](https://balsamiq.com) in the past and would definitely recommend. Has a free 30 day trial to play around with it.
