### ISSUE TITLE
Run report assessing use of ERA by authenticated, non-CCID, users

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/Hydranorth2#23]
As an administrator I want to know how many people with a non-CCID account have logged in to (Sufia6) ERA in the last 12 months so that we can communicate with users and and understand the scope of the change in authentication to CCID only access.

**Comment by pbinkley** [comment]
Report sent to Leah Feb. 16.

**Comment by sfbetz** [comment]
Rerun report and attach item type, url to each user.
