### ISSUE TITLE
Visibility settings on deposit

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/Hydranorth2#26]
As a user / administrator I want three visibility options when I deposit items into ERA: Open Access, CCID access, and Private.

**Comment by weiweishi** [comment]
And it should include Embargo option in the visibility view.

**Comment by sfbetz** [comment]
We think we can fix these items in ERA and migration can account for discrepancy.

**Comment by sfbetz** [comment]
"Henceforward" (p. binkley) authentication means CCID, means UA user.
