### ISSUE TITLE
Remove collections links and features in user dashboard

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/Hydranorth2#30]
As a user I do not want to see references to collections because I can’t do anything with those (since personal collections are disabled)

**Comment by weiweishi** [comment]
As a regular user, 
to remove
- [ ] Create Collection
- [ ] View Collections
- [ ] Collection Created 
  on the /dashboard page. 
- [ ] Tab of "My Collections" on the dashboard/works page
- [ ] Remove the Collection icon on the top banner
- [ ] Remove the "My Collections" scope from the search function
