### ISSUE TITLE
Suppress "sharing" functions

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/Hydranorth2#45]
As an administrator I want to suppress the ‘sharing’ function to simplify the deposit interface.

**Comment by weiweishi** [comment]
This is for IR requirement, and we might need to revisit this function for our research data requirements.

**Comment by weiweishi** [comment]
Also to remove
- [ ]  "Shares" from the top Dashboard dropdown menu. 
- [ ] "Works Shared with Me" tab
- [ ] "My Shares" from the search scope
