### ISSUE TITLE
Port user model, shibboleth setup to Hydranorth2

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/Hydranorth2#75]
To lock down the Community and collection CRUD to administrators, and allow all collections to be owned by a system account, we'll need to bring our user model, abilities, and permissions into Hydranorth2. This is, as always, also an opportunity to identify and cleanup any debt we might want to clear up as part of the move.

Throw out the legacy password columns/logic.

**Comment by murny** [comment]
Work for this is done in master. Still need work for getting authentication to work against Ist sample. Which is scoped out in issue #129 . Closing issue.
