### ISSUE TITLE
Set up admin group permissions & integrate w/ CCID sign-in

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/Hydranorth2#76]
Right now every user who needs admin privledges logs in to a special shared admin user. This is suboptimal. We would like to lock that account and just use it as a placeholding owner account for system-wide objects. We would also like to eliminate username/password login in general in favor of shibd/ccid.

To that end, we need to modify the abilities setup to grant admin privledges to any user account in an admin group, thereby allowing people like Leah to authenticate with their *own* CCID but gain admin privileges.

This may require investigation to ensure that when admin users edit system-owned items, they don't change ownership. If that happens we may need to investigate instead having a set of CCIDs which, when used, log in to the system account instead of a personal account.

Hydra-in-a-box uses https://github.com/RolifyCommunity/rolify

**Comment by murny** [comment]
Work for this is done in master.  Closing issue.
