### ISSUE TITLE
Create protected 'system' user account to own collections

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/Hydranorth2#77]
In current era I believe the admin account every admin shares owns these items, so it might make sense to designate this as the system account. We will want to:

- [x] ensure that every collection is always owned by this account (NEVERMIND)
- [ ] lock this account so that no one can ever log in to it (pending #76)

**Comment by murny** [comment]
Is this still required? A `system` user could have it's purposes. Such as using it as a global user for system notifications and other system tasks. But with the current requirements as far as I know, I can't see us needing it?

I think having works/collections/files/etc being owned by the user account who created them is much smarter and better for auditing purposes. Everything will be restricted on the role level of a user in hydranorth2 (admin roles will be the ones having authorisation over collections as far as I understand). And considering we don't delete users (I am assuming we only lock accounts?), we don't really need this for preservation either (aka assigning a deleted user's collections to a placeholder system account)? 

Also if we still want to do this, do we actually need a real user in the user table? Most objects in fedora do not have referential integrity to the users table and are just strings? You could just assign a `system` user as a string for these?

Either way it's not hard to seed  a `system` user in a seeds.rb that is locked on creation with a random password. But this will probably add a bunch of edge cases for us.  As we may not want to do a bunch of stuff for this account, such as not having this account show up on /users index, not listing/allowing it to be edited in places such as the admin gem we are planning, and much much more.

**Comment by mbarnett** [comment]
Yeah I'm fine with not pursuing this given everything you've outlined. The roles-based approach is a better solution to the problem anyways.
