### ISSUE TITLE
Establish basic pattern for tests

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/Hydranorth2#83]
Shane has identified some better patterns we could begin using in our new gems, particular with respect to centralizing a few test objects in features, to get away from the performance drag of constantly initializing and destroying ActiveFedora objects at the beginning of tests.

Could we use VCR to speed up Fedora interactions? (Tricia's idea)

**Comment by murny** [comment]
This has been completed. Closing Issue.

More details can be found in the PR #92
