### ISSUE TITLE
Evaluate whether or not we can tease out some shibd/omniauth integration to send back to community

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/Hydranorth2#84]
Evaluate whether or not we can tease out some shibd/omniauth integration that isn't site-specific that could be pushed back to the community. If we think there's anything there, float the idea by the community.

**Comment by pbinkley** [comment]
Time-box to 3 hours

**Comment by weiweishi** [comment]
- [ ] spec tests for user 
- [ ] small bug fixes
