### ISSUE TITLE
Admin Gem

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/Hydranorth2#87]
User stories from https://github.com/ualbertalib/HydraNorth/issues/833, discussed at backlog grooming 2016-11-23

**As an administrator, I want to have the ability to find and manage all items, so I can effectively administer ERA’s items:** - **complete**

-search and view all items (including private items not owned by me) 
-edit all items (including items I do not own)
-delete all items
-transfer ownership of all items (including items I do not own)
-share ownership of all items (including items I do not own)
-move items to and from all communities

**As an administrator, I want to access to all collection tasks, so I can effectively administer ERA’s communities and collections:**

-search for all communities and collections
-edit all communities and collections
-delete communities and collections
-add, delete, move multiple items to and from all communities, including private / embargoed items I do not own - the batch selection of items for moving should be available to admin and to normal users
-create communities and collections that appear in the deposit form and browsing pages

**As an administrator, I need top-level access to user management, so I can control and manage user accounts and functions.**
-restrict access to user list to administrators
-search all users
-view all users - *
-sort all users by name
-edit all users 
-assign roles to users
-delete all users
-login as a user and perform all that user’s tasks - *

**As an administrator, I need searching and sorting functions in my dashboard so I can find and manage files and collections easily.** - complete

-default sort in my files tab: by most recently added/edited
- be able to sort items in my files  by date added, title, author
  -search within my files

-differentiate between collections and communities (current creation form just has a tick box to distinguish communities from collections)
-collections to be sorted in my collections tab by title
-be able to sort items in my collections by title,  date created
-search to discover collections as such

**As an administrator I want to be able to easily communicate with users so I can keep them updated on changes to ERA.** see #47 

-post banner messages on the home page and every page (Sufia just has home page) (we took it out of Natasha's layout for HN1)
-ability to add notifications to the dashboard (default Sufia functionality is fine)
-(highlighted collections / researchers is not a priority for HN2 - will reconsider when digitization content moves in)

@leahvanderjagt does not see a use case for devolving any admin rights to users (such as department members). Changes to collection descriptions etc. will be mediated by ERA admin.

**Comment by leahvanderjagt** [comment]
FYI, can confirm now that we don't need a Collection Owner role.
