### ISSUE TITLE
Analytics Gem

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/Hydranorth2#88]
We will start with Google Analytics as in HN1, but with 
- improved presentation (e.g. move graph to main item page? Needs user testing)
- add aggregation by collection (high priority for stakeholders)

Post-HN2 we want to consider:
- better coverage (e.g. non-html downloads)
- better privacy
- broader coverage of usage (Lagotto-style: Twitter mentions etc., based on DOIs, ORCIDs, etc.)

Numbers needed:

- view
- download

We need:

- clarity - what events count for what number
- consistency - the numbers should be accurate, should not change arbitrarily
- aggregate stats by collection (this is high priority for admin)

(fragment rescued from Admin epic):

(Move Analytics to a different gem)
**As an administrator I want to be able to run detailed analytics and reports so i can identify areas of success and improvement for ERA, and communicate its value to external stakeholders.** - post-PCDM

-item / collection (aggregated items, all items) / community (aggregated items, all items) / researcher (uploads, aggregated items, all items)
- collection analytics are visible to everyone

**Comment by sfbetz** [comment]
-ability to display most popular articles: in repository, in community, in a collection - and push these numbers into site somewhere
-we are curious about what analytics we can pull from the Google Analytics API? What are the possibilities? 
Here's a DSpace example
eg: https://tspace.library.utoronto.ca/handle/1807/25019/statistics

**Comment by leahvanderjagt** [comment]
-how difficult would it be to integrate the free altmetric badges to ERA? could this be a short term easy win for metrics enhancement? https://www.altmetric.com/products/free-tools/institutional-repository-badges/
