### ISSUE TITLE
Server-side IIIF rendering

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/Hydranorth2#94]
(Capturing some thoughts and discussion on Slack this morning)

We know that Fedora performance in retrieving large sets of ordered PCDM nodes (such as the pages in a book) is very slow (on hydra-tech there's a report of 30 seconds for 1000 pages). This will put us back in the unacceptably slow page rendering that we had with Collections when we first started on Sufia. We have [very large items](http://peel.library.ualberta.ca/bibliography/2962.47.html) in Peel. It will be worse, in fact, since pages have metadata (the page number and some type codes such as "cover" or "title page") that will also have to be retrieved for each page in the set. 

We can mitigate the problem by relying entirely on pre-generated IIIF manifests. A large blob of json will be stored and served, and the problem of dealing with the large number of pages is transferred to the client. 

But if we need to serve users who turn off javascript in their browser (~1%) or have accessibility issues with using dynamic pages), we'll need a static presentation as well as client-side IIIF. Perhaps a community project to develop a gem that renders javascript-free presentations from a IIIF manifest, to produce static pages like on the current Peel site, would be needed. This would be similar to the [jekyll-iiif plugin](https://pbinkley.github.io/jekyll-iiif/), which renders static pages as well as serving IIIF json to the client.

**Comment by sfbetz** [comment]
Hello! I think we should capture our big sky thoughts in an external doc, and only add issues to this repo that we will actively be working on based on our big roadmap (and tied directly to an epic). I'll make us a folder and we can discuss strategy at stakeholders meeting.

**Comment by pbinkley** [comment]
This issue was moved to ualbertalib/HydraNorth-Bluesky#1
