### ISSUE TITLE
Remaining Triplestore work

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/Hydranorth2#96]
_From @weiweishi on October 24, 2016 18:43_

This is the remaining work after our initial triplestore ticket #139 
## Triplestore Works
- [ ] Test fcrepo-indexing-triplestore to make sure that automatically update is working properly
- [ ] Import PREMIS metadata into the triplestore
- [x] Decision on the selection of triplestore for production
- [ ] Setup triplestore production server
- [ ] Index Fedora4 production server to selected triplestore

_Copied from original issue: ualbertalib/HydraNorth#1306_

**Comment by pbinkley** [comment]
_From @zschoenb on November 2, 2016 20:3_

Can we see if the Premis metadata can be made operational and available in the triplestore? This data could serve an important role in auditing as time goes on.

**Comment by pbinkley** [comment]
_From @piyapongch on November 2, 2016 20:49_

There are some sample data in Fuseki. You need to select audit dataset and
query. It has 59 triples. The subject is still not correct. I will need to
do more testing.

Piyapong.

**Comment by sfarnel** [comment]
Based on review and testing [processes](https://docs.google.com/document/d/1vV4YQvEGniNb6KEzzDhm1fcbTHnlfbzLNfyZQWQI2L4/edit?usp=sharing), metadata team recommends Blazegraph for production triplestore.
